# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 23:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active_users', '0002_auto_20170228_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_active',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('day', 'user')]),
        ),
    ]
